const routes = {
    signIn: { id: 'signIn', name: 'signIn', path: '/signin' },
    signUp: { id: 'signUp', name: 'signUp', path: '/signup' },
    forgetPassword: { id: 'forgetPassword', name: 'forgetPassword', path: '/forget-password' },
    myFavourites: { id: 'myFavourites', name: 'My Favourites', path: '/my-favourites' },
    homepage: { id: 'homepage', name: 'Homepage', path: '/' },
    setting: { id: 'settting', name: 'Setting', path: '/settings/[index]' },
    myDetails: { id: 'myDetails', name: 'My Details', path: '/settings/my-details' },
    myProjects: { id: 'myProjects', name: 'My Projects', path: '/settings/my-projects' },
    downloadHistory: { id: 'downloadHistory', name: 'Download History', path: '/settings/download-history' },
    project: { id: 'projects', name: 'projects', path: '/projects/[project_id]' },
    projects: { id: 'projects', name: 'projects', path: '/projects' },
    userVerified: { id: 'userVerified', name: 'userVerified', path: '/user-verified' },
    errorPage: { id: 'errorPage', name: 'errorPage', path: '/404' },
    checkout: { id: 'checkout', name: 'checkout', path: '/checkout' },
    billingSubscription: { id: 'billingSubscription', name: 'billingSubscription', path: '/settings/billing-subscription' },
    youtubeClaimSupport: { id: 'youtubeClaimSupport', name: 'youtubeClaimSupport', path: '/settings/youtube-claim-support' },
    generalSupport: { id: 'generalSupport', name: 'generalSupport', path: '/settings/general-support' },
    changePassword: { id: 'changePassword', name: 'changePassword', path: '/settings/change-password' },
    terms: { id: 'terms', name: 'Terms and condition', path: '/terms-conditions' },
    privacyPolicy: { id: 'privacyPolicy', name: 'privacyPolicy', path: '/privacy-policy' },
    licenceAgreement: { id: 'licenceAgreement', name: 'licenceAgreement', path: '/licensing-agreement' },
    searchResult: { id: 'searchResult', name: 'searchResult', path: '/search-result' },
    musicDetailsPage: { id: 'musicDetailsPage', name: 'Music Details', path: '/music-details/[id]' },
    footageDetailsPage: { id: 'footageDetailsPage', name: 'Footage Details', path: '/footage-details/[id]' },
    footageDetails: { id: 'footageDetailsPage', name: 'Footage Details', path: '/footage-details' },
    faqPage: { id: 'faqPage', name: 'Faq Page', path: '/faq-page' },
    paymentFailed: { id: 'paymentFailed', name: 'paymentFailed', path: '/payment-failed' },
    paymentSuccess: { id: 'paymentSuccess', name: 'paymentSuccess', path: '/payment-success' },
    musicSearchResult: { id: 'musicSearchResult', name: 'musicSearchResult', path: '/music-search-result' },
};

export default routes;
